config/routes.rb
Irdb3::Application.routes.draw do

  resources :bookshelves

  resources :user_profiles

  resources :postings do
    resources :reviews
    resources :recommendations
  end

  devise_for :users

  root 'pages#home'

end

app/models/bookshelf.rb
class Bookshelf < ActiveRecord::Base
end

app/models/posting.rb
class Posting < ActiveRecord::Base

  belongs_to :user,
    inverse_of: :postings

  has_many :reviews,
    inverse_of: :posting

  has_many :recommendations,
    inverse_of: :posting

  validates_presence_of :title
  validates_presence_of :url
  validates_format_of :url,
    with: URI::regexp(%w(http https))

  validates_presence_of :category
  validates_inclusion_of :category,
    in: ['Book', 'Video', 'Article']
  validates_presence_of :description

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :recommendations
  belongs_to :posting,
    inverse_of: :recommendations

  validates_presence_of :user
  validates_presence_of :posting

  validates_uniqueness_of :posting_id,
  scope: :user_id
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates_presence_of :posting
  validates_presence_of :body
  validates_presence_of :user

  belongs_to :posting,
    inverse_of: :reviews,
    dependent: :destroy

  belongs_to :user,
    inverse_of: :reviews
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :postings,
    inverse_of: :user

  has_many :reviews,
    through: :postings,
    inverse_of: :user

  has_many :recommendations,
    inverse_of: :user

  has_one :user_profile,
    inverse_of: :user

  validates_presence_of :user_name
  validates_presence_of :first_name
  validates_presence_of :last_name

  validates_uniqueness_of :user_name, :case_sensitive => false, :message => "has already been taken"
  validates_uniqueness_of :email, :case_sensitive => false, :message => "has already been taken"

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :user_profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:user_name, :first_name, :last_name]
  end
end

app/controllers/bookshelves_controller.rb
class BookshelvesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  def new
    @posting = Posting.new
  end

  def index
    @q = Posting.search(params[:q])
    @postings = @q.result.order("id").page(params[:page]).per(5)
  end

  def create
    if current_user
      @posting = Posting.new(posting_params)
      @posting.user_id = current_user.id

      if @posting.save
        flash[:notice] = 'Your post has been added to Ruby Classics.'
        redirect_to postings_path(@posting)
      else
        render :new
      end
    else
      redirect_to(postings_path, notice: "You must sign in to add titles")
    end
  end

  def show
    @posting = Posting.find(params[:id])
  end

  protected
  def posting_params
    params.require(:posting).permit(
      :title, :url, :description, :category)
  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def create
    if current_user
      posting = Posting.find(params[:posting_id])
      recommendation = Recommendation.new
      recommendation.user_id = current_user.id
      recommendation.posting_id = posting.id
      if recommendation.save
        redirect_to(:back, notice: "You recommended #{posting.title}")
      else
        redirect_to(:back, notice: "You already recommended #{posting.title}")
      end
    else
      redirect_to(:back, notice: "You must sign in to recommend titles")
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @posting = Posting.find(params[:posting_id])
  end

  def index
    if params[:posting_id]
      @posting = Posting.find( params[:posting_id] )
      @reviews = Review.where( posting_id: @posting.id )
    else
      @posting = nil
      @reviews = Review.all
    end
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @posting = Posting.find( params[:posting_id] )
    @review.posting_id = @posting.id

    if @review.save
      flash[:notice] = 'Thank you for your review.'
      redirect_to posting_reviews_path(@posting)
    else
      render :new
    end
  end

  protected
  def review_params
    params.require(:review).permit(:body, :posting_id)
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def new
    @user_profile = UserProfile.new
  end

  def index
    @q = UserProfile.search(params[:q])
    @user_profiles = @q.result.order("id").page(params[:page]).per(5)
  end

  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user_profile.user_id = current_user.id

    if @user_profile.save
      flash[:notice] = 'Wow, your profile page looks great.'
      redirect_to user_profiles_path(@user_profile)
    else
      render :new
    end
  end

  def show
    @user_profile = UserProfile.find(user_profile_params)
  end


  protected
  def user_profile_params
    params.require(:user_profile).permit(:hometown, :twitter,
      :github, :blog, :website, :for_hire, :for_pairing)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :last_name, :first_name)
  end

end

app/helpers/bookshelves_helper.rb
module BookshelvesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row top-buffer">


  <div class="large-3 columns">
   <h3 class="home-boxes"><em>Accelerate your learning</em></h3>
  </div>

  <%= link_to postings_path do %>
    <div class="large-3 columns">
      <h3 class="home-boxes"><span class="sparkle">Learn</span> from trusted members of the community</h3>
    </div>
  <% end %>

  <%= link_to new_posting_path do %>
    <div class="large-3 columns">
      <h3 class="home-boxes"><span class="sparkle">Share</span> resources that helped you the most</h3>
    </div>
  <% end %>

  <%= link_to user_profiles_path do %>
    <div class="large-3 columns">
      <h3 class="home-boxes"><span class="sparkle">Connect</span> with other Rubyists near you</h3>
    </div>
  <% end %>
</div>

app/views/postings/index.html.erb
<h2>The best online resources for Ruby developers</h2>
<div>
  <div>
    <%= search_form_for @q do |f| %>
      <div class="field">
        <%= f.text_field :title_cont, placeholder: 'Search for titles' %>
      </div>
      <div class="actions"><%= f.submit "Search" %></div>
    <% end %>
  </div>

  <% @postings.each do |posting| %>
    <ul class="no-bullet">
      <li><%= posting.category %></li>
      <strong><li><%= link_to posting.title, posting.url %></li></strong>
      <li><%= posting.description %></li>
    </ul>

    <ul class="inline-list">
      <li><%= link_to 'Reviews', posting_reviews_path(posting) %></li>
      <li><em>Added by <%= User.where(id: posting.user_id).first.full_name %></em></li>
      <li><em>Recommended by <%= pluralize(posting.recommendations.length, "user") %></em></li>
      <li><%= button_to 'Recommend', posting_recommendations_path(posting_id: posting.id), class:'small secondary', render: :back %></li>
    </ul>
   <hr />
  <%- end -%>
</div>

<%= paginate @postings %>
<br />
<%= link_to 'Share an online resource', new_posting_path %>

app/views/postings/new.html.erb
<h3>Do you know an awesome online resource for Rubyists?</h3>
<% if current_user %>
  <p>Share it with the community and earn some good karma</p>

  <%= simple_form_for(@posting) do |f| %>
    <%= f.input :title, label: false, placeholder: 'Title' %>
    <%= f.input :url, label: false, placeholder: 'Website' %>
    <%= f.input :description, label: false, placeholder: 'Description' %>
    <%= f.input :category, label: false, collection: ['Book', 'Video', 'Article'], selected: 'Book', input_html: {style: 'width: 150px'}%>
      <%= f.button :submit, 'Add this title' %>
  <% end %>
<%- else -%>
  <p>You must <%= link_to 'sign in', new_user_session_path %> to add a title.</p>
<%- end -%>

<%= link_to 'Cancel', postings_path %>

app/views/reviews/index.html.erb
<% if @reviews %>
  <h3><%= "Reviews for #{@posting.title}" %></h3>

  <% if !current_user %>
    <p>You must <%= link_to 'sign in', new_user_session_path %> to review this title.</p>
  <%- else -%>
    <% @reviews.each do |review| %>
    <ul class="no-bullet">
      <li><%= content_tag :td, review.body %></li>
      <li><em>-<%= content_tag :td, review.user.full_name %></em></li>
    </ul>
    <% end %>
  <% end %>

  <%- if @reviews.length == 0 %>
    <%= link_to "Be the first to review this", new_posting_review_path %>
  <% else %>
    <%= link_to "Review this", new_posting_review_path %>
  <% end %>
<% end %>

app/views/reviews/new.html.erb
<% @review.errors.full_messages.each do | error | %>
  <%= content_tag :p, error %>
<% end %>

<h3>Review: <%= link_to @posting.title, @posting.url %></h3>
<% if !current_user %>
  <p>You must sign in to review this title.</p>
<%- end -%>

<%= simple_form_for([@posting, @review]) do |f| %>
  <%= f.input_field :body, placeholder: 'What I think about this resource' %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Cancel', posting_reviews_path(@posting) %>

app/views/user_profiles/index.html.erb
<h3>The best minds in the Ruby community</h3>
<div>
  <div>
    <%= search_form_for @q do |f| %>
      <div class="field">
        <%= f.text_field :about_me_cont, placeholder: 'Search information about the members' %>
      </div>
      <div class="actions"><%= f.submit "Search" %></div>
    <% end %>
  </div>

  <% @user_profiles.each do |profile| %>
  <div class="row">
    <div class="large-3 columns">
      <ul class="no-bullet">
        <% username = User.where(id: profile.user_id).first.user_name %>
        <li><strong><%= username %></strong></li>
        <li><%= profile.hometown %></li>
        <li><%= link_to profile.twitter, "http://www.twitter.com/#{profile.twitter}" %></li>
        <li><%= link_to 'Github', profile.github %></li>
        <li><%= link_to 'Blog', profile.blog %></li>
        <li><%= link_to 'Website', profile.website %></li>
        <% if profile.for_hire %>
           <li>Available for hire</li>
        <%- end -%>
        <% if profile.for_pairing %>
          <li>Available for pairing</li>
        <%- end -%>
      </ul>
    </div>

    <div class="large-8 columns">
      <ul class="no-bullet">
        <li><em>About Me: </em><%= profile.about_me %></li>
        <li><em>Ruby links shared </em><%= Posting.where(user_id: profile.user_id).count  %> </li>
        <li><em>Ruby links recommended </em><%= Recommendation.where(user_id: profile.user_id).count  %> </li>
        <li><em>Ruby links reviewed </em><%= Review.where(user_id: profile.user_id).count  %> </li>
      </ul>
    </div>

  <hr />
  </div>
  <%- end -%>

</div>

<%= paginate @user_profiles %>
<br />
<%= link_to 'Share a Ruby resource', new_posting_path %>
<br />

app/views/user_profiles/new.html.erb
<h3>Share your expertise with fellow Rubyists</h3>
<p>Post your online information and availability for pairing, jobs and other opportunities</p>

<%= simple_form_for(@user_profile) do |f|  %>
  <%= f.input :hometown %>
  <%= f.input :twitter, placeholder: '@username' %>
  <%= f.input :github, placeholder: 'http://www.github.com/username'  %>
  <%= f.input :blog, placeholder: 'http://www.mywebsite.com' %>
  <%= f.input :website, placeholder: 'http://www.mywebsite.com' %>
  <%= f.input :about_me, placeholder: 'What are you working on? What are you passionate about?' %>

  <%= f.label 'Available for hire' %>
  <%= f.collection_radio_buttons :for_pairing, [[true, 'Yes'] ,[false, 'No']], :first, :last %>

  <%= f.label 'Available for pair programming' %>
  <span class="custom radio"></span><%= f.collection_radio_buttons :for_hire, [[true, 'Yes'] ,[false, 'No']], :first, :last, input_html: {style: 'display:none' }%>

  <%= f.button :submit, 'Create my profile' %>
<% end %>

<%= link_to 'Cancel', postings_path %>